// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mfa.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MfaCreateDataRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	ProviderID           string   `protobuf:"bytes,2,opt,name=ProviderID,proto3" json:"ProviderID,omitempty"`
	AppName              string   `protobuf:"bytes,3,opt,name=AppName,proto3" json:"AppName,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	QrSize               int32    `protobuf:"varint,5,opt,name=QrSize,proto3" json:"QrSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MfaCreateDataRequest) Reset()         { *m = MfaCreateDataRequest{} }
func (m *MfaCreateDataRequest) String() string { return proto.CompactTextString(m) }
func (*MfaCreateDataRequest) ProtoMessage()    {}
func (*MfaCreateDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_mfa_8f3acb8e3f367f98, []int{0}
}
func (m *MfaCreateDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MfaCreateDataRequest.Unmarshal(m, b)
}
func (m *MfaCreateDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MfaCreateDataRequest.Marshal(b, m, deterministic)
}
func (dst *MfaCreateDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MfaCreateDataRequest.Merge(dst, src)
}
func (m *MfaCreateDataRequest) XXX_Size() int {
	return xxx_messageInfo_MfaCreateDataRequest.Size(m)
}
func (m *MfaCreateDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MfaCreateDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MfaCreateDataRequest proto.InternalMessageInfo

func (m *MfaCreateDataRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *MfaCreateDataRequest) GetProviderID() string {
	if m != nil {
		return m.ProviderID
	}
	return ""
}

func (m *MfaCreateDataRequest) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *MfaCreateDataRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *MfaCreateDataRequest) GetQrSize() int32 {
	if m != nil {
		return m.QrSize
	}
	return 0
}

type MfaCreateDataResponse struct {
	SecretKey            string   `protobuf:"bytes,1,opt,name=SecretKey,proto3" json:"SecretKey,omitempty"`
	URL                  string   `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	QrCodeURL            string   `protobuf:"bytes,3,opt,name=QrCodeURL,proto3" json:"QrCodeURL,omitempty"`
	ImageBased           string   `protobuf:"bytes,4,opt,name=ImageBased,proto3" json:"ImageBased,omitempty"`
	RecoveryCode         []string `protobuf:"bytes,5,rep,name=RecoveryCode,proto3" json:"RecoveryCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MfaCreateDataResponse) Reset()         { *m = MfaCreateDataResponse{} }
func (m *MfaCreateDataResponse) String() string { return proto.CompactTextString(m) }
func (*MfaCreateDataResponse) ProtoMessage()    {}
func (*MfaCreateDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mfa_8f3acb8e3f367f98, []int{1}
}
func (m *MfaCreateDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MfaCreateDataResponse.Unmarshal(m, b)
}
func (m *MfaCreateDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MfaCreateDataResponse.Marshal(b, m, deterministic)
}
func (dst *MfaCreateDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MfaCreateDataResponse.Merge(dst, src)
}
func (m *MfaCreateDataResponse) XXX_Size() int {
	return xxx_messageInfo_MfaCreateDataResponse.Size(m)
}
func (m *MfaCreateDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MfaCreateDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MfaCreateDataResponse proto.InternalMessageInfo

func (m *MfaCreateDataResponse) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *MfaCreateDataResponse) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *MfaCreateDataResponse) GetQrCodeURL() string {
	if m != nil {
		return m.QrCodeURL
	}
	return ""
}

func (m *MfaCreateDataResponse) GetImageBased() string {
	if m != nil {
		return m.ImageBased
	}
	return ""
}

func (m *MfaCreateDataResponse) GetRecoveryCode() []string {
	if m != nil {
		return m.RecoveryCode
	}
	return nil
}

type MfaCheckDataRequest struct {
	ProviderID           string   `protobuf:"bytes,1,opt,name=ProviderID,proto3" json:"ProviderID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MfaCheckDataRequest) Reset()         { *m = MfaCheckDataRequest{} }
func (m *MfaCheckDataRequest) String() string { return proto.CompactTextString(m) }
func (*MfaCheckDataRequest) ProtoMessage()    {}
func (*MfaCheckDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_mfa_8f3acb8e3f367f98, []int{2}
}
func (m *MfaCheckDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MfaCheckDataRequest.Unmarshal(m, b)
}
func (m *MfaCheckDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MfaCheckDataRequest.Marshal(b, m, deterministic)
}
func (dst *MfaCheckDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MfaCheckDataRequest.Merge(dst, src)
}
func (m *MfaCheckDataRequest) XXX_Size() int {
	return xxx_messageInfo_MfaCheckDataRequest.Size(m)
}
func (m *MfaCheckDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MfaCheckDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MfaCheckDataRequest proto.InternalMessageInfo

func (m *MfaCheckDataRequest) GetProviderID() string {
	if m != nil {
		return m.ProviderID
	}
	return ""
}

func (m *MfaCheckDataRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *MfaCheckDataRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type MfaCheckDataResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MfaCheckDataResponse) Reset()         { *m = MfaCheckDataResponse{} }
func (m *MfaCheckDataResponse) String() string { return proto.CompactTextString(m) }
func (*MfaCheckDataResponse) ProtoMessage()    {}
func (*MfaCheckDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mfa_8f3acb8e3f367f98, []int{3}
}
func (m *MfaCheckDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MfaCheckDataResponse.Unmarshal(m, b)
}
func (m *MfaCheckDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MfaCheckDataResponse.Marshal(b, m, deterministic)
}
func (dst *MfaCheckDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MfaCheckDataResponse.Merge(dst, src)
}
func (m *MfaCheckDataResponse) XXX_Size() int {
	return xxx_messageInfo_MfaCheckDataResponse.Size(m)
}
func (m *MfaCheckDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MfaCheckDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MfaCheckDataResponse proto.InternalMessageInfo

func (m *MfaCheckDataResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *MfaCheckDataResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_mfa_8f3acb8e3f367f98, []int{4}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*MfaCreateDataRequest)(nil), "proto.MfaCreateDataRequest")
	proto.RegisterType((*MfaCreateDataResponse)(nil), "proto.MfaCreateDataResponse")
	proto.RegisterType((*MfaCheckDataRequest)(nil), "proto.MfaCheckDataRequest")
	proto.RegisterType((*MfaCheckDataResponse)(nil), "proto.MfaCheckDataResponse")
	proto.RegisterType((*Error)(nil), "proto.Error")
}

func init() { proto.RegisterFile("mfa.proto", fileDescriptor_mfa_8f3acb8e3f367f98) }

var fileDescriptor_mfa_8f3acb8e3f367f98 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xcb, 0x4e, 0xc2, 0x40,
	0x14, 0xb5, 0x40, 0xab, 0xbd, 0xb2, 0x30, 0x23, 0x92, 0x06, 0x88, 0xc1, 0x59, 0xb1, 0x62, 0x81,
	0x5f, 0x20, 0x8f, 0x05, 0x51, 0x8c, 0x0c, 0xe1, 0x03, 0xc6, 0x72, 0xc1, 0x46, 0x6a, 0xeb, 0x4c,
	0x21, 0xc1, 0x0f, 0xd1, 0x6f, 0xf0, 0x2f, 0xcd, 0x3c, 0x48, 0x0b, 0xb2, 0xea, 0x9c, 0x73, 0x6e,
	0xef, 0x3d, 0x73, 0xee, 0x80, 0x1f, 0x2f, 0x79, 0x37, 0x15, 0x49, 0x96, 0x10, 0x57, 0x7f, 0xe8,
	0xb7, 0x03, 0xb5, 0xc9, 0x92, 0x0f, 0x04, 0xf2, 0x0c, 0x87, 0x3c, 0xe3, 0x0c, 0x3f, 0x37, 0x28,
	0x33, 0x52, 0x07, 0x6f, 0x2e, 0x51, 0x8c, 0x87, 0x81, 0xd3, 0x76, 0x3a, 0x3e, 0xb3, 0x88, 0xdc,
	0x02, 0xbc, 0x88, 0x64, 0x1b, 0x2d, 0xb4, 0x56, 0xd2, 0x5a, 0x81, 0x21, 0x01, 0x9c, 0x3f, 0xa4,
	0xe9, 0x33, 0x8f, 0x31, 0x28, 0x6b, 0x71, 0x0f, 0x49, 0x0d, 0xdc, 0x51, 0xcc, 0xa3, 0x75, 0x50,
	0xd1, 0xbc, 0x01, 0x6a, 0xce, 0x54, 0xcc, 0xa2, 0x2f, 0x0c, 0xdc, 0xb6, 0xd3, 0x71, 0x99, 0x45,
	0xf4, 0xd7, 0x81, 0x9b, 0x23, 0x63, 0x32, 0x4d, 0x3e, 0x24, 0x92, 0x16, 0xf8, 0x33, 0x0c, 0x05,
	0x66, 0x8f, 0xb8, 0xb3, 0xe6, 0x72, 0x82, 0x5c, 0x41, 0x79, 0xce, 0x9e, 0xac, 0x31, 0x75, 0x54,
	0xf5, 0x53, 0x31, 0x48, 0x16, 0xa8, 0x78, 0xe3, 0x29, 0x27, 0xd4, 0x7d, 0xc6, 0x31, 0x5f, 0x61,
	0x9f, 0x4b, 0x5c, 0x58, 0x6b, 0x05, 0x86, 0x50, 0xa8, 0x32, 0x0c, 0x93, 0x2d, 0x8a, 0x9d, 0xfa,
	0x25, 0x70, 0xdb, 0xe5, 0x8e, 0xcf, 0x0e, 0x38, 0xca, 0xe1, 0x5a, 0x59, 0x7d, 0xc3, 0xf0, 0xbd,
	0x18, 0xe1, 0x61, 0x54, 0xce, 0xbf, 0xa8, 0xf2, 0x88, 0x4b, 0x07, 0x11, 0x13, 0xa8, 0xe8, 0x51,
	0xc6, 0xab, 0x3e, 0x53, 0x66, 0xd6, 0x94, 0x8f, 0xb0, 0x61, 0xd4, 0xc1, 0x63, 0x28, 0x37, 0xeb,
	0x4c, 0xf7, 0xbf, 0x60, 0x16, 0x11, 0x0a, 0xee, 0x48, 0x88, 0x44, 0xe8, 0xd6, 0x97, 0xbd, 0xaa,
	0xd9, 0x7a, 0x57, 0x73, 0xcc, 0x48, 0xf4, 0xce, 0xd6, 0xa8, 0x9d, 0x4d, 0x50, 0x4a, 0xbe, 0x42,
	0xeb, 0x72, 0x0f, 0x7b, 0x3f, 0x0e, 0xc0, 0x64, 0xc9, 0x67, 0x28, 0xb6, 0x51, 0x88, 0x64, 0x04,
	0x9e, 0x59, 0x08, 0x69, 0xda, 0x86, 0xa7, 0xde, 0x4e, 0xa3, 0x75, 0x5a, 0x34, 0x96, 0xe9, 0x19,
	0xe9, 0x83, 0xab, 0x6f, 0x42, 0x1a, 0x85, 0xc2, 0xa3, 0xf4, 0x1a, 0xcd, 0x93, 0xda, 0xbe, 0xc7,
	0xab, 0xa7, 0xd5, 0xfb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x9c, 0xfd, 0x06, 0xd3, 0x02,
	0x00, 0x00,
}
