// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mfa.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MfaCreateDataRequest struct {
	AppName              string   `protobuf:"bytes,1,opt,name=AppName,proto3" json:"AppName,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	QrSize               int32    `protobuf:"varint,4,opt,name=QrSize,proto3" json:"QrSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MfaCreateDataRequest) Reset()         { *m = MfaCreateDataRequest{} }
func (m *MfaCreateDataRequest) String() string { return proto.CompactTextString(m) }
func (*MfaCreateDataRequest) ProtoMessage()    {}
func (*MfaCreateDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_mfa_cbfc1a0add9bd51e, []int{0}
}
func (m *MfaCreateDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MfaCreateDataRequest.Unmarshal(m, b)
}
func (m *MfaCreateDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MfaCreateDataRequest.Marshal(b, m, deterministic)
}
func (dst *MfaCreateDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MfaCreateDataRequest.Merge(dst, src)
}
func (m *MfaCreateDataRequest) XXX_Size() int {
	return xxx_messageInfo_MfaCreateDataRequest.Size(m)
}
func (m *MfaCreateDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MfaCreateDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MfaCreateDataRequest proto.InternalMessageInfo

func (m *MfaCreateDataRequest) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *MfaCreateDataRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *MfaCreateDataRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *MfaCreateDataRequest) GetQrSize() int32 {
	if m != nil {
		return m.QrSize
	}
	return 0
}

type MfaCreateDataResponse struct {
	SecretKey            string   `protobuf:"bytes,1,opt,name=SecretKey,proto3" json:"SecretKey,omitempty"`
	URL                  string   `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	QrCodeURL            string   `protobuf:"bytes,3,opt,name=QrCodeURL,proto3" json:"QrCodeURL,omitempty"`
	ImageBased           string   `protobuf:"bytes,4,opt,name=ImageBased,proto3" json:"ImageBased,omitempty"`
	RecoveryCode         []string `protobuf:"bytes,5,rep,name=RecoveryCode,proto3" json:"RecoveryCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MfaCreateDataResponse) Reset()         { *m = MfaCreateDataResponse{} }
func (m *MfaCreateDataResponse) String() string { return proto.CompactTextString(m) }
func (*MfaCreateDataResponse) ProtoMessage()    {}
func (*MfaCreateDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mfa_cbfc1a0add9bd51e, []int{1}
}
func (m *MfaCreateDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MfaCreateDataResponse.Unmarshal(m, b)
}
func (m *MfaCreateDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MfaCreateDataResponse.Marshal(b, m, deterministic)
}
func (dst *MfaCreateDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MfaCreateDataResponse.Merge(dst, src)
}
func (m *MfaCreateDataResponse) XXX_Size() int {
	return xxx_messageInfo_MfaCreateDataResponse.Size(m)
}
func (m *MfaCreateDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MfaCreateDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MfaCreateDataResponse proto.InternalMessageInfo

func (m *MfaCreateDataResponse) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *MfaCreateDataResponse) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *MfaCreateDataResponse) GetQrCodeURL() string {
	if m != nil {
		return m.QrCodeURL
	}
	return ""
}

func (m *MfaCreateDataResponse) GetImageBased() string {
	if m != nil {
		return m.ImageBased
	}
	return ""
}

func (m *MfaCreateDataResponse) GetRecoveryCode() []string {
	if m != nil {
		return m.RecoveryCode
	}
	return nil
}

type MfaCheckDataRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MfaCheckDataRequest) Reset()         { *m = MfaCheckDataRequest{} }
func (m *MfaCheckDataRequest) String() string { return proto.CompactTextString(m) }
func (*MfaCheckDataRequest) ProtoMessage()    {}
func (*MfaCheckDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_mfa_cbfc1a0add9bd51e, []int{2}
}
func (m *MfaCheckDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MfaCheckDataRequest.Unmarshal(m, b)
}
func (m *MfaCheckDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MfaCheckDataRequest.Marshal(b, m, deterministic)
}
func (dst *MfaCheckDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MfaCheckDataRequest.Merge(dst, src)
}
func (m *MfaCheckDataRequest) XXX_Size() int {
	return xxx_messageInfo_MfaCheckDataRequest.Size(m)
}
func (m *MfaCheckDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MfaCheckDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MfaCheckDataRequest proto.InternalMessageInfo

func (m *MfaCheckDataRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *MfaCheckDataRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type MfaCheckDataResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MfaCheckDataResponse) Reset()         { *m = MfaCheckDataResponse{} }
func (m *MfaCheckDataResponse) String() string { return proto.CompactTextString(m) }
func (*MfaCheckDataResponse) ProtoMessage()    {}
func (*MfaCheckDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mfa_cbfc1a0add9bd51e, []int{3}
}
func (m *MfaCheckDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MfaCheckDataResponse.Unmarshal(m, b)
}
func (m *MfaCheckDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MfaCheckDataResponse.Marshal(b, m, deterministic)
}
func (dst *MfaCheckDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MfaCheckDataResponse.Merge(dst, src)
}
func (m *MfaCheckDataResponse) XXX_Size() int {
	return xxx_messageInfo_MfaCheckDataResponse.Size(m)
}
func (m *MfaCheckDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MfaCheckDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MfaCheckDataResponse proto.InternalMessageInfo

func (m *MfaCheckDataResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *MfaCheckDataResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_mfa_cbfc1a0add9bd51e, []int{4}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*MfaCreateDataRequest)(nil), "proto.MfaCreateDataRequest")
	proto.RegisterType((*MfaCreateDataResponse)(nil), "proto.MfaCreateDataResponse")
	proto.RegisterType((*MfaCheckDataRequest)(nil), "proto.MfaCheckDataRequest")
	proto.RegisterType((*MfaCheckDataResponse)(nil), "proto.MfaCheckDataResponse")
	proto.RegisterType((*Error)(nil), "proto.Error")
}

func init() { proto.RegisterFile("mfa.proto", fileDescriptor_mfa_cbfc1a0add9bd51e) }

var fileDescriptor_mfa_cbfc1a0add9bd51e = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x6e, 0xf2, 0x30,
	0x10, 0xfd, 0xf2, 0x41, 0x42, 0x33, 0x65, 0x51, 0x4d, 0x29, 0xb2, 0x00, 0x55, 0xc8, 0x2b, 0x56,
	0x2c, 0xa8, 0x7a, 0x00, 0xfe, 0x16, 0xa8, 0xa5, 0x12, 0x46, 0x1c, 0xc0, 0x0d, 0x03, 0x45, 0x25,
	0x4d, 0x6a, 0x07, 0x24, 0x7a, 0x91, 0x9e, 0xa1, 0xb7, 0xac, 0x62, 0x1b, 0xf1, 0x23, 0xba, 0x8a,
	0xdf, 0x7b, 0xe3, 0x79, 0x6f, 0xc6, 0x81, 0x30, 0x5e, 0xc8, 0x76, 0xaa, 0x92, 0x2c, 0x41, 0xdf,
	0x7c, 0xf8, 0x16, 0x2a, 0xe3, 0x85, 0xec, 0x2b, 0x92, 0x19, 0x0d, 0x64, 0x26, 0x05, 0x7d, 0x6e,
	0x48, 0x67, 0xc8, 0xa0, 0xd4, 0x4d, 0xd3, 0x17, 0x19, 0x13, 0xf3, 0x9a, 0x5e, 0x2b, 0x14, 0x7b,
	0x88, 0x55, 0x08, 0x66, 0x9a, 0xd4, 0x68, 0xc0, 0xfe, 0x1b, 0xc1, 0x21, 0xac, 0x80, 0x3f, 0x8c,
	0xe5, 0x6a, 0xcd, 0x0a, 0x86, 0xb6, 0x20, 0xaf, 0x9e, 0xa8, 0xe9, 0xea, 0x8b, 0x58, 0xb1, 0xe9,
	0xb5, 0x7c, 0xe1, 0x10, 0xff, 0xf1, 0xe0, 0xee, 0xcc, 0x58, 0xa7, 0xc9, 0x87, 0x26, 0x6c, 0x40,
	0x38, 0xa5, 0x48, 0x51, 0xf6, 0x44, 0x3b, 0xe7, 0x7d, 0x20, 0xf0, 0x06, 0x0a, 0x33, 0xf1, 0xec,
	0xac, 0xf3, 0x63, 0x5e, 0x3f, 0x51, 0xfd, 0x64, 0x4e, 0x39, 0x6f, 0xbd, 0x0f, 0x04, 0xde, 0x03,
	0x8c, 0x62, 0xb9, 0xa4, 0x9e, 0xd4, 0x34, 0x37, 0x19, 0x42, 0x71, 0xc4, 0x20, 0x87, 0xb2, 0xa0,
	0x28, 0xd9, 0x92, 0xda, 0xe5, 0x57, 0x98, 0xdf, 0x2c, 0xb4, 0x42, 0x71, 0xc2, 0xf1, 0x2e, 0xdc,
	0xe6, 0x51, 0xdf, 0x28, 0x7a, 0x3f, 0x5e, 0x11, 0x42, 0xd1, 0x5c, 0xb1, 0x19, 0xcd, 0xf9, 0xaf,
	0xe5, 0x70, 0x61, 0xd7, 0x7c, 0x68, 0xe1, 0x86, 0xad, 0x42, 0x20, 0x48, 0x6f, 0xd6, 0x99, 0xe9,
	0x72, 0x25, 0x1c, 0x42, 0x0e, 0xfe, 0x50, 0xa9, 0x44, 0x99, 0x36, 0xd7, 0x9d, 0xb2, 0x7d, 0xb4,
	0xb6, 0xe1, 0x84, 0x95, 0xf8, 0xa3, 0xab, 0x39, 0x09, 0xe2, 0xbb, 0x20, 0x0c, 0x4a, 0x63, 0xd2,
	0x5a, 0x2e, 0xc9, 0x25, 0xd9, 0xc3, 0xce, 0xb7, 0x07, 0x30, 0x5e, 0xc8, 0x29, 0xa9, 0xed, 0x2a,
	0x22, 0x1c, 0x42, 0x60, 0x1f, 0x01, 0xeb, 0xce, 0xe4, 0xd2, 0xff, 0x50, 0x6b, 0x5c, 0x16, 0xed,
	0x18, 0xfc, 0x1f, 0xf6, 0xc0, 0x37, 0xd3, 0x61, 0xed, 0xa8, 0xf0, 0x6c, 0x63, 0xb5, 0xfa, 0x45,
	0x6d, 0xdf, 0xe3, 0x35, 0x30, 0xea, 0xc3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x08, 0x3b, 0x0b,
	0xd3, 0xa6, 0x02, 0x00, 0x00,
}
